// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgzlmfbwtfazmobddwgn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhnemxtZmJ3dGZhem1vYmRkd2duIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MTM2ODgsImV4cCI6MjA2MzI4OTY4OH0.y2NJn82G36ClSKDc2eq_IGAH5aSYMN_4g6SDBFJSlzw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);